/**
 * Created by LM on 14-2-28.
 */
'use strict';
var db = require('./db');

exports.findBySql=function(sql,args,callback){
    var connection=db().getConnection(function(err,connection){
        if(err){
            console.log("获得connection出现错误:"+err);
            throw err;
        }
        connection.query(sql,args,function(err, rows, fields){
            if (err){
                console.log(err);
                rows=[];
            }
            callback(rows);
            connection.release();
        });
    });
};
exports.insertBySql=function(sql,args,callback){
    var connection=db().getConnection(function(err,connection){
        if(err){
            console.log("获得connection出现错误:"+err);
            throw err;
        }
        connection.query(sql,args,function(err,info){
            if (err){
                console.log(err);
                info={};
            }
            callback(info,args);
            connection.release();
        });
    });
};
exports.executeBySql=function(sqlArray,argsArray,callback){
    if(sqlArray.length!==argsArray.length)return;
    db().getConnection(function(err,connection){
        if(err){
            console.log("获得connection出现错误:"+err);
            throw err;
        }
        connection.removeAllListeners();
        connection.on("error",function(err){
            console.log("出现错误，已回滚"+err);
            connection.rollback(function(err){
                if (err) {
                    console.log("回滚失败，怎么会这样呢");
                    throw err;
                }
            });
            connection.release();
        });
        connection.beginTransaction(function(err) {
            if (err) throw err;
            for(var i=0;i<sqlArray.length;i++){
                connection.query(sqlArray[i],argsArray[i]);
            }
            connection.commit(function(err){
                if(err)throw err;
                callback();
                connection.release();
            });
        });
    });
};

/*使用嵌套方式完成事务中多条增删改
function executeBySqlRecursion (connection,sqlArray,argsArray,index,callback){
    connection.query(sqlArray[index],argsArray[index],function(err, result){
        if (err) {
            connection.rollback(function() {
                throw err;
            });
        }
        console.log(result);
        if(index<sqlArray.length-1){
            executeBySqlRecursion(connection,sqlArray,argsArray,index+1,callback);
        }
        else{
            callback();
        }
    });
}
exports.executeBySql=function(sqlArray,argsArray,callback){
    if(sqlArray.length!==argsArray.length)return;
    var connection=pool.getConnection(function(err,connection){
        connection.beginTransaction(function(err) {
            if (err) { throw err; }
            executeBySqlRecursion(connection,sqlArray,argsArray,0,function(){
                connection.commit(function(err) {
                    if (err) {
                        connection.rollback(function() {
                            throw err;
                        });
                    }
                    console.log('success!');
                    connection.release();
                    callback();
                });
            });
        });
    });
};*/
exports.initDB=function(){
    db().getConnection(function(err,connection){
        /*-----------------------创建数据库---------------------------*/
        connection.query("use incar");
        var argsArray=[];
        argsArray.push({
            code:0x0000,
            unit:"伏特",
            tip:"电压",
            description:"蓄电池电压",
            valueMin:0,
            valueMax:18,
            fmt:"%1.f"
        });
        argsArray.push({
            code:0x0001,
            unit:"",
            tip:"故障码个数",
            description:"存储在电子控制单元中的故障码个数",
            valueMin:0,
            valueMax:127,
            fmt:"%d"
        });
        argsArray.push({
            code:0x0002,
            unit:"",
            tip:"故障灯状态",
            description:"故障灯状态(关,开)",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x0003,
            unit:"",
            tip:"冻结帧故障码",
            description:"对应所存储的冻结帧的故障码（P C B U）",
            valueMin:null,
            valueMax:null,
            fmt:"%s%04X"
        });
        argsArray.push({
            code:0x0004,
            unit:"",
            tip:"燃油系统1状态",
            description:"燃油系统1状态（OL CL OL-Drive）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x0005,
            unit:"",
            tip:"燃油系统2状态",
            description:"燃油系统2状态（OL CL OL-Drive）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x0006,
            unit:"%",
            tip:"计算负荷值",
            description:"计算负荷值",
            valueMin:0,
            valueMax:100.0,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x0007,
            unit:"℃",
            tip:"发动机冷却温度",
            description:"发动机冷却温度",
            valueMin:-40,
            valueMax:215,
            fmt:"%d"
        });
        argsArray.push({
            code:0x0008,
            unit:"%",
            tip:"第1列短期燃油修正",
            description:"第1列的短期燃油修正",
            valueMin:-100,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x0009,
            unit:"%",
            tip:"第3列短期燃油修正",
            description:"第3列的短期燃油修正",
            valueMin:-100,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x000A,
            unit:"%",
            tip:"第1列长期燃油修正",
            description:"第1列的长期燃油修正",
            valueMin:-100,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x000B,
            unit:"%",
            tip:"第3列长期燃油修正",
            description:"第3列的长期燃油修正",
            valueMin:-100,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x000C,
            unit:"%",
            tip:"第2列短期燃油修正",
            description:"第2列的短期燃油修正",
            valueMin:-100,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x000D,
            unit:"%",
            tip:"第4列短期燃油修正",
            description:"第4列的短期燃油修正",
            valueMin:-100,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x000E,
            unit:"%",
            tip:"第2列长期燃油修正",
            description:"第2列的长期燃油修正",
            valueMin:-100,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x000E,
            unit:"%",
            tip:"第4列长期燃油修正",
            description:"第4列的长期燃油修正",
            valueMin:-100,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x0010,
            unit:"千帕",
            tip:"油轨压力",
            description:"油轨压力",
            valueMin:0,
            valueMax:765,
            fmt:"%d"
        });
        argsArray.push({
            code:0x0011,
            unit:"千帕",
            tip:"进气歧管绝对压力",
            description:"进气歧管绝对压力",
            valueMin:0,
            valueMax:255,
            fmt:"%d"
        });
        argsArray.push({
            code:0x0012,
            unit:"转/分",
            tip:"发动机转速",
            description:"发动机转速",
            valueMin:0,
            valueMax:16383.75,
            fmt:"%.0f"
        });
        argsArray.push({
            code:0x0013,
            unit:"km/h",
            tip:"车速",
            description:"车速",
            valueMin:0,
            valueMax:255,
            fmt:"%d"
        });
        argsArray.push({
            code:0x0014,
            unit:"。",
            tip:"1号汽缸点火正时提前角",
            description:"1号汽缸点火正时提前角",
            valueMin:-64,
            valueMax:63.5,
            fmt:"%.0f"
        });
        argsArray.push({
            code:0x0015,
            unit:"℃",
            tip:"进气温度",
            description:"进气温度",
            valueMin:-40,
            valueMax:215,
            fmt:"%d"
        });
        argsArray.push({
            code:0x0016,
            unit:"克/秒",
            tip:"空气流量",
            description:"空气流量传感器的空气流量",
            valueMin:0,
            valueMax:655.35,
            fmt:"%.2f"
        });
        argsArray.push({
            code:0x0017,
            unit:"%",
            tip:"绝对节气门位置",
            description:"绝对节气门位置",
            valueMin:0,
            valueMax:100.0,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x0018,
            unit:"",
            tip:"二次空气状态指令",
            description:"二次空气状态指令（UPS DNS OFF）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x0019,
            unit:"",
            tip:"氧传感器的位置",
            description:"氧传感器的位置（O2S11 O2S12 O2S13）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x001A,
            unit:"伏特",
            tip:"1列氧感1输出电压",
            description:"第1列氧传感器1的输出电压",
            valueMin:0,
            valueMax:1.275,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x001B,
            unit:"%",
            tip:"1列氧感1短期燃油修正",
            description:"第1列氧传感器1的短期燃油修正",
            valueMin:-100,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x001C,
            unit:"伏特",
            tip:"1列氧感2输出电压",
            description:"第1列氧传感器2的输出电压",
            valueMin:0,
            valueMax:1.275,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x001D,
            unit:"%",
            tip:"1列氧感2短期燃油修正",
            description:"第1列氧传感器2的短期燃油修正",
            valueMin:-100,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x001E,
            unit:"伏特",
            tip:"1列氧感3输出电压",
            description:"第1列氧传感器3的输出电压",
            valueMin:0,
            valueMax:1.275,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x001F,
            unit:"%",
            tip:"1列氧感3短期燃油修正",
            description:"第1列氧传感器3的短期燃油修正",
            valueMin:-100,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x0020,
            unit:"伏特",
            tip:"1列氧感4输出电压",
            description:"第1列氧传感器4的输出电压",
            valueMin:0,
            valueMax:1.275,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0021,
            unit:"%",
            tip:"1列氧感4短期燃油修正",
            description:"第1列氧传感器4的短期燃油修正",
            valueMin:-100,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x0022,
            unit:"伏特",
            tip:"2列氧感1输出电压",
            description:"第2列氧传感器1的输出电压",
            valueMin:0,
            valueMax:1.275,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0023,
            unit:"%",
            tip:"2列氧感1短期燃油修正",
            description:"第2列氧传感器1的短期燃油修正",
            valueMin:-100,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x0024,
            unit:"伏特",
            tip:"2列氧感2输出电压",
            description:"第2列氧传感器2的输出电压",
            valueMin:0,
            valueMax:1.275,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0025,
            unit:"%",
            tip:"2列氧感2短期燃油修正",
            description:"第2列氧传感器2的短期燃油修正",
            valueMin:-100,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x0026,
            unit:"伏特",
            tip:"2列氧感3输出电压",
            description:"第2列氧传感器3的输出电压",
            valueMin:0,
            valueMax:1.275,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0027,
            unit:"%",
            tip:"2列氧感3短期燃油修正",
            description:"第2列氧传感器3的短期燃油修正",
            valueMin:-100,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x0028,
            unit:"伏特",
            tip:"2列氧感4输出电压",
            description:"第2列氧传感器4的输出电压",
            valueMin:0,
            valueMax:1.275,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0029,
            unit:"%",
            tip:"2列氧感4短期燃油修正",
            description:"第2列氧传感器4的短期燃油修正",
            valueMin:-100,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x002A,
            unit:"",
            tip:"1列氧感1等效比",
            description:"第1列氧传感器1的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x002B,
            unit:"伏特",
            tip:"1列氧感1电压",
            description:"第1列氧传感器1的电压",
            valueMin:0,
            valueMax:7.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x002C,
            unit:"",
            tip:"1列氧感2等效比",
            description:"第1列氧传感器2的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x002D,
            unit:"伏特",
            tip:"1列氧感2电压",
            description:"第1列氧传感器2的电压",
            valueMin:0,
            valueMax:7.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x002E,
            unit:"",
            tip:"1列氧感3等效比",
            description:"第1列氧传感器3的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x002F,
            unit:"伏特",
            tip:"1列氧感3电压",
            description:"第1列氧传感器3的电压",
            valueMin:0,
            valueMax:7.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0030,
            unit:"",
            tip:"1列氧感4等效比",
            description:"第1列氧传感器4的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0031,
            unit:"伏特",
            tip:"1列氧感4电压",
            description:"第1列氧传感器4的电压",
            valueMin:0,
            valueMax:7.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0032,
            unit:"",
            tip:"2列氧感1等效比",
            description:"第2列氧传感器1的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0033,
            unit:"伏特",
            tip:"2列氧感1电压",
            description:"第2列氧传感器1的电压",
            valueMin:0,
            valueMax:7.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0034,
            unit:"",
            tip:"2列氧感2等效比",
            description:"第2列氧传感器2的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0035,
            unit:"伏特",
            tip:"2列氧感2电压",
            description:"第2列氧传感器2的电压",
            valueMin:0,
            valueMax:7.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0036,
            unit:"",
            tip:"2列氧感3等效比",
            description:"第2列氧传感器3的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0037,
            unit:"伏特",
            tip:"2列氧感3电压",
            description:"第2列氧传感器3的电压",
            valueMin:0,
            valueMax:7.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0038,
            unit:"",
            tip:"2列氧感4等效比",
            description:"第2列氧传感器4的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0039,
            unit:"伏特",
            tip:"2列氧感4电压",
            description:"第2列氧传感器4的电压",
            valueMin:0,
            valueMax:7.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x003A,
            unit:"",
            tip:"1列氧感1等效比",
            description:"第1列氧传感器1的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x003B,
            unit:"毫安",
            tip:"1列氧感1电流",
            description:"第1列氧传感器1的电流",
            valueMin:-128,
            valueMax:127.996,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x003C,
            unit:"",
            tip:"1列氧感2等效比",
            description:"第1列氧传感器2的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x003D,
            unit:"毫安",
            tip:"1列氧感2电流",
            description:"第1列氧传感器2的电流",
            valueMin:-128,
            valueMax:127.996,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x003E,
            unit:"",
            tip:"1列氧感3等效比",
            description:"第1列氧传感器3的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x003F,
            unit:"毫安",
            tip:"1列氧感3电流",
            description:"第1列氧传感器3的电流",
            valueMin:-128,
            valueMax:127.996,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0040,
            unit:"",
            tip:"1列氧感4等效比",
            description:"第1列氧传感器4的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0041,
            unit:"毫安",
            tip:"1列氧感4电流",
            description:"第1列氧传感器4的电流",
            valueMin:-128,
            valueMax:127.996,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0042,
            unit:"",
            tip:"2列氧感1等效比",
            description:"第2列氧传感器1的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0043,
            unit:"毫安",
            tip:"2列氧感1电流",
            description:"第2列氧传感器1的电流",
            valueMin:-128,
            valueMax:127.996,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0044,
            unit:"",
            tip:"2列氧感2等效比",
            description:"第2列氧传感器2的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0045,
            unit:"毫安",
            tip:"2列氧感2电流",
            description:"第2列氧传感器2的电流",
            valueMin:-128,
            valueMax:127.996,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0046,
            unit:"",
            tip:"2列氧感3等效比",
            description:"第2列氧传感器3的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0047,
            unit:"毫安",
            tip:"2列氧感3电流",
            description:"第2列氧传感器3的电流",
            valueMin:-128,
            valueMax:127.996,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0048,
            unit:"",
            tip:"2列氧感4等效比",
            description:"第2列氧传感器4的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0049,
            unit:"毫安",
            tip:"2列氧感4电流",
            description:"第2列氧传感器4的电流",
            valueMin:-128,
            valueMax:127.996,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x004A,
            unit:"",
            tip:"OBD系统车辆设计要求",
            description:"OBD系统车辆设计要求（[OBDII][EOBD]...）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x004B,
            unit:"",
            tip:"氧传感器位置",
            description:"氧传感器的位置（O2S11 O2S12）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x004C,
            unit:"伏特",
            tip:"1列感1输出电压",
            description:"第1列传感器1的输出电压",
            valueMin:0,
            valueMax:1.275,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x004D,
            unit:"%",
            tip:"1列感1短期燃油修正",
            description:"第1列传感器1的短期燃油修正",
            valueMin:-100.00,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x004E,
            unit:"伏特",
            tip:"1列感2输出电压",
            description:"第1列传感器2的输出电压",
            valueMin:0,
            valueMax:1.275,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x004F,
            unit:"%",
            tip:"1列感2短期燃油修正",
            description:"第1列传感器2的短期燃油修正",
            valueMin:-100.00,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x0050,
            unit:"伏特",
            tip:"2列感1输出电压",
            description:"第2列传感器1的输出电压",
            valueMin:0,
            valueMax:1.275,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0051,
            unit:"%",
            tip:"2列感1短期燃油修正",
            description:"第2列传感器1的短期燃油修正",
            valueMin:-100.00,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x0052,
            unit:"伏特",
            tip:"2列感2输出电压",
            description:"第2列传感器2的输出电压",
            valueMin:0,
            valueMax:1.275,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0053,
            unit:"%",
            tip:"2列感2短期燃油修正",
            description:"第2列传感器2的短期燃油修正",
            valueMin:-100.00,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x0054,
            unit:"伏特",
            tip:"3列感1输出电压",
            description:"第3列传感器1的输出电压",
            valueMin:0,
            valueMax:1.275,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0055,
            unit:"%",
            tip:"3列感1短期燃油修正",
            description:"第3列传感器1的短期燃油修正",
            valueMin:-100.00,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x0056,
            unit:"伏特",
            tip:"3列感2输出电压",
            description:"第3列传感器2的输出电压",
            valueMin:0,
            valueMax:1.275,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0057,
            unit:"%",
            tip:"3列感2短期燃油修正",
            description:"第3列传感器2的短期燃油修正",
            valueMin:-100.00,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x0058,
            unit:"伏特",
            tip:"4列感1输出电压",
            description:"第4列传感器1的输出电压",
            valueMin:0,
            valueMax:1.275,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0059,
            unit:"%",
            tip:"4列感1短期燃油修正",
            description:"第4列传感器1的短期燃油修正",
            valueMin:-100.00,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x005A,
            unit:"伏特",
            tip:"4列感2输出电压",
            description:"第4列传感器2的输出电压",
            valueMin:0,
            valueMax:1.275,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x005B,
            unit:"%",
            tip:"4列感2短期燃油修正",
            description:"第4列传感器2的短期燃油修正",
            valueMin:-100.00,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x005C,
            unit:"",
            tip:"1列氧感1等效比",
            description:"第1列氧传感器1的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x005D,
            unit:"伏特",
            tip:"1列氧感1电压",
            description:"第1列氧传感器1的电压",
            valueMin:0,
            valueMax:7.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x005E,
            unit:"",
            tip:"1列氧感2等效比",
            description:"第1列氧传感器2的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x005F,
            unit:"伏特",
            tip:"1列氧感2电压",
            description:"第1列氧传感器2的电压",
            valueMin:0,
            valueMax:7.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0060,
            unit:"",
            tip:"2列氧感1等效比",
            description:"第2列氧传感器1的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0061,
            unit:"伏特",
            tip:"2列氧感1电压",
            description:"第2列氧传感器1的电压",
            valueMin:0,
            valueMax:7.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0062,
            unit:"",
            tip:"2列氧感2等效比",
            description:"第2列氧传感器2的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0063,
            unit:"伏特",
            tip:"2列氧感2电压",
            description:"第2列氧传感器2的电压",
            valueMin:0,
            valueMax:7.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0064,
            unit:"",
            tip:"3列氧感1等效比",
            description:"第3列氧传感器1的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0065,
            unit:"伏特",
            tip:"3列氧感1电压",
            description:"第3列氧传感器1的电压",
            valueMin:0,
            valueMax:7.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0066,
            unit:"",
            tip:"3列氧感2等效比",
            description:"第3列氧传感器2的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0069,
            unit:"伏特",
            tip:"3列氧感2电压",
            description:"第3列氧传感器2的电压",
            valueMin:0,
            valueMax:7.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0068,
            unit:"",
            tip:"4列氧感1等效比",
            description:"第4列氧传感器1的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0069,
            unit:"伏特",
            tip:"4列氧感1电压",
            description:"第4列氧传感器1的电压",
            valueMin:0,
            valueMax:7.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x006A,
            unit:"",
            tip:"4列氧感2等效比",
            description:"第4列氧传感器2的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x006B,
            unit:"伏特",
            tip:"4列氧感2电压",
            description:"第4列氧传感器2的电压",
            valueMin:0,
            valueMax:7.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x006C,
            unit:"",
            tip:"1列氧感1等效比",
            description:"第1列氧传感器1的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x006D,
            unit:"毫安",
            tip:"1列氧感1电流",
            description:"第1列氧传感器1的电流",
            valueMin:-128,
            valueMax:127.996,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x006E,
            unit:"",
            tip:"1列氧感2等效比",
            description:"第1列氧传感器2的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x006F,
            unit:"毫安",
            tip:"1列氧感2电流",
            description:"第1列氧传感器2的电流",
            valueMin:-128,
            valueMax:127.996,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0070,
            unit:"",
            tip:"2列氧感1等效比",
            description:"第2列氧传感器1的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0071,
            unit:"毫安",
            tip:"2列氧感1电流",
            description:"第2列氧传感器1的电流",
            valueMin:-128,
            valueMax:127.996,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0072,
            unit:"",
            tip:"2列氧感2等效比",
            description:"第2列氧传感器2的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0073,
            unit:"毫安",
            tip:"2列氧感2电流",
            description:"第2列氧传感器2的电流",
            valueMin:-128,
            valueMax:127.996,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0074,
            unit:"",
            tip:"3列氧感1等效比",
            description:"第3列氧传感器1的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0075,
            unit:"毫安",
            tip:"3列氧感1电流",
            description:"第3列氧传感器1的电流",
            valueMin:-128,
            valueMax:127.996,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0076,
            unit:"",
            tip:"3列氧感2等效比",
            description:"第3列氧传感器2的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0077,
            unit:"毫安",
            tip:"3列氧感2电流",
            description:"第3列氧传感器2的电流",
            valueMin:-128,
            valueMax:127.996,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0078,
            unit:"",
            tip:"4列氧感1等效比",
            description:"第4列氧传感器1的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0079,
            unit:"毫安",
            tip:"4列氧感1电流",
            description:"第4列氧传感器1的电流",
            valueMin:-128,
            valueMax:127.996,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x007A,
            unit:"",
            tip:"4列氧感2等效比",
            description:"第4列氧传感器2的等效比",
            valueMin:0,
            valueMax:1.999,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x007B,
            unit:"毫安",
            tip:"4列氧感2电流",
            description:"第4列氧传感器2的电流",
            valueMin:-128,
            valueMax:127.996,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x007C,
            unit:"",
            tip:"辅助输入状态",
            description:"辅助输入状态（关 开）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x007D,
            unit:"秒",
            tip:"自发动机启动的时间",
            description:"自发动机启动的时间",
            valueMin:0,
            valueMax:65535,
            fmt:"%d"
        });
        argsArray.push({
            code:0x007E,
            unit:"千米",
            tip:"在故障指示灯激活状态下行驶的里程",
            description:"在故障指示灯激活状态下行驶的里程",
            valueMin:0,
            valueMax:65535,
            fmt:"%d"
        });
        argsArray.push({
            code:0x007F,
            unit:"千帕",
            tip:"相对于歧管真空度的油轨压力",
            description:"相对于歧管真空度油轨压力",
            valueMin:0,
            valueMax:5177.27,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x0080,
            unit:"千帕",
            tip:"相对于大气压力的油轨压力",
            description:"相对于大气压力的油轨压力",
            valueMin:0,
            valueMax:655350,
            fmt:"%d"
        });
        argsArray.push({
            code:0x0081,
            unit:"%",
            tip:"废气再循环系统指令开度",
            description:"废气再循环系统指令开度",
            valueMin:0,
            valueMax:100,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x0082,
            unit:"%",
            tip:"EGR开度误差",
            description:"EGR开度误差（实际开度-指令开度）/指令开度*100%",
            valueMin:-100,
            valueMax:99.2,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x0083,
            unit:"%",
            tip:"蒸发冲洗控制指令",
            description:"蒸发冲洗控制指令",
            valueMin:0,
            valueMax:100,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x0084,
            unit:"%",
            tip:"燃油液位输入",
            description:"燃油液位输入",
            valueMin:0,
            valueMax:100,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x0085,
            unit:"",
            tip:"故码清除暖机次数",
            description:"故障码清除后的暖机次数",
            valueMin:0,
            valueMax:255,
            fmt:"%d"
        });
        argsArray.push({
            code:0x0086,
            unit:"千米",
            tip:"故码清除后里程",
            description:"故障码清除后的行驶里程",
            valueMin:0,
            valueMax:65535,
            fmt:"%d"
        });
        argsArray.push({
            code:0x0087,
            unit:"Pa",
            tip:"蒸发系统蒸汽压力",
            description:"蒸发系统的蒸汽压力",
            valueMin:-8192.0,
            valueMax:0.0,
            fmt:"%.2f"
        });
        argsArray.push({
            code:0x0088,
            unit:"千帕",
            tip:"大气压",
            description:"大气压",
            valueMin:0,
            valueMax:255,
            fmt:"%d"
        });
        argsArray.push({
            code:0x0089,
            unit:"C",
            tip:"1列感1催化剂温度",
            description:"第1列传感器1的催化剂温度",
            valueMin:-40,
            valueMax:6513.5,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x008A,
            unit:"C",
            tip:"2列感1催化剂温度",
            description:"第2列传感器1的催化剂温度",
            valueMin:-40,
            valueMax:6513.5,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x008B,
            unit:"C",
            tip:"1列感2催化剂温度",
            description:"第1列传感器2的催化剂温度",
            valueMin:-40,
            valueMax:6513.5,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x008C,
            unit:"C",
            tip:"2列感2催化剂温度",
            description:"第2列传感器2的催化剂温度",
            valueMin:-40,
            valueMax:6513.5,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x008D,
            unit:"",
            tip:"失火监控",
            description:"失火监控（有效 无效）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x008E,
            unit:"",
            tip:"燃油系统监控",
            description:"燃油系统监控（有效 无效）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x008F,
            unit:"",
            tip:"综合元件监控",
            description:"综合元件监控（有效 无效）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x0090,
            unit:"",
            tip:"失火监控",
            description:"失火监控（完成 未完成）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x0091,
            unit:"",
            tip:"燃油系统监控",
            description:"燃油系统监控（完成 未完成）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x0092,
            unit:"",
            tip:"综合元件监控",
            description:"综合元件监控（完成 未完成）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x0093,
            unit:"",
            tip:"催化剂监控",
            description:"催化剂监控（有效 无效）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x0094,
            unit:"",
            tip:"加热型催化剂监控",
            description:"加热型催化剂监控（有效 无效）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x0016,
            unit:"",
            tip:"燃油蒸发系统监控",
            description:"燃油蒸发系统监控（有效 无效）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x0096,
            unit:"",
            tip:"二次空气系统监控",
            description:"二次空气系统监控（有效 无效）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x0097,
            unit:"",
            tip:"空调系统制冷剂监控",
            description:"空调系统制冷剂监控（有效 无效）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x0098,
            unit:"",
            tip:"氧传感器监控",
            description:"氧传感器监控（有效 无效）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x0099,
            unit:"",
            tip:"氧传感器加热器监控",
            description:"氧传感器加热器监控（有效 无效）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x009A,
            unit:"",
            tip:"废气再循环系统监控",
            description:"废气再循环系统监控（有效 无效）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x009B,
            unit:"",
            tip:"催化剂监控",
            description:"催化剂监控（完成 未完成）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x009C,
            unit:"",
            tip:"加热型催化剂监控",
            description:"加热型催化剂监控（完成 未完成）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x009D,
            unit:"",
            tip:"燃油蒸发系统监控",
            description:"燃油蒸发系统监控（完成 未完成）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x009E,
            unit:"",
            tip:"二次空气系统监控",
            description:"二次空气系统监控（完成 未完成）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x009F,
            unit:"",
            tip:"空调系统制冷剂监控",
            description:"空调系统制冷剂监控（完成 未完成）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x00A0,
            unit:"",
            tip:"氧传感器监控",
            description:"氧传感器监控（完成 未完成）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x00A1,
            unit:"",
            tip:"氧传感器加热器监控",
            description:"氧传感器加热器监控（完成 未完成）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x00A2,
            unit:"",
            tip:"废气再循环系统监控",
            description:"废气再循环系统监控（完成 未完成）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x00A3,
            unit:"伏特",
            tip:"控制单元电压",
            description:"控制单元电压",
            valueMin:0,
            valueMax:65.535,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x00A4,
            unit:"%",
            tip:"绝对负载值",
            description:"绝对负载值",
            valueMin:0,
            valueMax:25700.0,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x00A5,
            unit:"",
            tip:"等效比指令",
            description:"等效比指令",
            valueMin:0,
            valueMax:1.99,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x00A6,
            unit:"%",
            tip:"相对节气门位置",
            description:"相对节气门位置",
            valueMin:0,
            valueMax:100.0,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x00A7,
            unit:"C",
            tip:"环境空气温度",
            description:"环境空气温度",
            valueMin:-40,
            valueMax:215,
            fmt:"%d"
        });
        argsArray.push({
            code:0x00A8,
            unit:"%",
            tip:"绝对节气门位置B",
            description:"绝对节气门位置B",
            valueMin:0,
            valueMax:100.0,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x00A9,
            unit:"%",
            tip:"绝对节气门位置C",
            description:"绝对节气门位置C",
            valueMin:0,
            valueMax:100.0,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x00AA,
            unit:"%",
            tip:"加速踏板位置D",
            description:"加速踏板位置D",
            valueMin:0,
            valueMax:100.0,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x00AB,
            unit:"%",
            tip:"加速踏板位置E",
            description:"加速踏板位置E",
            valueMin:0,
            valueMax:100.0,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x00AC,
            unit:"%",
            tip:"加速踏板位置F",
            description:"加速踏板位置F",
            valueMin:0,
            valueMax:100.0,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x00AD,
            unit:"%",
            tip:"节气门执行器控制指令",
            description:"节气门执行器控制指令",
            valueMin:0,
            valueMax:100.0,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x00AE,
            unit:"分钟",
            tip:"故障灯激活下发动机运转时间",
            description:"故障指示灯处于激活状态下的发动机运转时间",
            valueMin:0,
            valueMax:65535,
            fmt:"%d"
        });
        argsArray.push({
            code:0x00AF,
            unit:"分钟",
            tip:"故障码清除后时间",
            description:"自故障码清除后的时间",
            valueMin:0,
            valueMax:65535,
            fmt:"%d"
        });
        argsArray.push({
            code:0x00B0,
            unit:"",
            tip:"最大等效比",
            description:"最大等效比",
            valueMin:0,
            valueMax:255,
            fmt:"%d"
        });
        argsArray.push({
            code:0x00B1,
            unit:"伏特",
            tip:"氧传感器最大电压",
            description:"氧传感器最大电压",
            valueMin:0,
            valueMax:255,
            fmt:"%d"
        });
        argsArray.push({
            code:0x00B2,
            unit:"豪安",
            tip:"氧传感器最大电流",
            description:"氧传感器最大电流",
            valueMin:0,
            valueMax:255,
            fmt:"%d"
        });
        argsArray.push({
            code:0x00B3,
            unit:"千帕",
            tip:"进气歧管最大绝对压力",
            description:"进气歧管最大绝对压力",
            valueMin:0,
            valueMax:2550,
            fmt:"%d"
        });
        argsArray.push({
            code:0x00B4,
            unit:"加仑/秒",
            tip:"空传最大流量",
            description:"空气流量传感器的最大流量",
            valueMin:0,
            valueMax:2550,
            fmt:"%d"
        });
        argsArray.push({
            code:0x00B5,
            unit:"",
            tip:"当前燃油类型",
            description:"车辆当前使用的燃油类型（Protocol GAS）",
            valueMin:null,
            valueMax:null,
            fmt:"%s"
        });
        argsArray.push({
            code:0x00B6,
            unit:"%",
            tip:"酒精燃料百分比",
            description:"酒精燃料百分比",
            valueMin:0,
            valueMax:100,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x00B7,
            unit:"千帕",
            tip:"蒸汽绝对压力",
            description:"蒸汽系统蒸汽绝对压力",
            valueMin:0,
            valueMax:327.675,
            fmt:"%.3f"
        });
        argsArray.push({
            code:0x00B8,
            unit:"帕",
            tip:"蒸汽压力",
            description:"蒸汽系统蒸汽压力",
            valueMin:-32767,
            valueMax:32768,
            fmt:"%d"
        });
        argsArray.push({
            code:0x00B9,
            unit:"%",
            tip:"1列氧传2短期修正",
            description:"第1列氧传感器2的短期燃油修正",
            valueMin:-100,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x00BA,
            unit:"%",
            tip:"3列氧传2短期修正",
            description:"第3列氧传感器2的短期燃油修正",
            valueMin:-100,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x00BB,
            unit:"%",
            tip:"1列氧传2长期修正",
            description:"第1列氧传感器2的长期燃油修正",
            valueMin:-100,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x00BC,
            unit:"%",
            tip:"3列氧传2长期修正",
            description:"第3列氧传感器2的长期燃油修正",
            valueMin:-100,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x00BD,
            unit:"%",
            tip:"2列氧传2短期修正",
            description:"第2列氧传感器2的短期燃油修正",
            valueMin:-100,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x00BE,
            unit:"%",
            tip:"4列氧传2短期修正",
            description:"第4列氧传感器2的短期燃油修正",
            valueMin:-100,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x00BF,
            unit:"%",
            tip:"2列氧传2长期修正",
            description:"第2列氧传感器2的长期燃油修正",
            valueMin:-100,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x00C0,
            unit:"%",
            tip:"4列氧传2长期修正",
            description:"第四列氧传感器2的长期燃油修正",
            valueMin:-100,
            valueMax:99.22,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x00C1,
            unit:"千帕",
            tip:"油轨绝对压力",
            description:"油轨绝对压力",
            valueMin:0,
            valueMax:2550,
            fmt:"%d"
        });
        argsArray.push({
            code:0x00C2,
            unit:"%",
            tip:"加速板相对位置",
            description:"加速踏板相对位置",
            valueMin:0,
            valueMax:100,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x00C3,
            unit:"%",
            tip:"电池组剩余寿命",
            description:"混合电池组剩余寿命",
            valueMin:0,
            valueMax:100.0,
            fmt:"%.1f"
        });
        argsArray.push({
            code:0x00C4,
            unit:"摄氏度",
            tip:"机油温度",
            description:"发动机机油温度",
            valueMin:-40,
            valueMax:210,
            fmt:"%d"
        });
        argsArray.push({
            code:0x00C5,
            unit:"度",
            tip:"喷油正时角",
            description:"喷油正时角",
            valueMin:-210,
            valueMax:301.992,
            fmt:"%.2f"
        });
        argsArray.push({
            code:0x00C6,
            unit:"升/小时",
            tip:"油耗率",
            description:"发动机耗油率",
            valueMin:0,
            valueMax:3276.75,
            fmt:"%.2f"
        });
        argsArray.push({
            code:0x00C7,
            unit:"",
            tip:"设计排放要求",
            description:"车辆设计的排放物要求（[---] [EURO C]）",
            valueMin:null,
            valueMax:null,
            fmt:"%d"
        });
        argsArray.push({
            code:0x00C8,
            unit:"%",
            tip:"要求转矩百分比",
            description:"驾驶员要求的发动机转矩百分比",
            valueMin:-125,
            valueMax:130,
            fmt:"%d"
        });
        argsArray.push({
            code:0x00C9,
            unit:"",
            tip:"实际转矩百分比",
            description:"发动机实际转矩百分比",
            valueMin:-125,
            valueMax:130,
            fmt:"%d"
        });
        argsArray.push({
            code:0x00CA,
            unit:"",
            tip:"基准转矩",
            description:"发动机基准转矩",
            valueMin:0,
            valueMax:65535,
            fmt:"%d"
        });
        argsArray.push({
            code:0x00CB,
            unit:"%",
            tip:"点1转矩百分比",
            description:"发动机在怠速点1的转矩百分比",
            valueMin:-125,
            valueMax:130,
            fmt:"%d"
        });
        argsArray.push({
            code:0x00CC,
            unit:"%",
            tip:"点2转矩百分比",
            description:"发动机在怠速点2的转矩百分比",
            valueMin:-125,
            valueMax:130,
            fmt:"%d"
        });
        argsArray.push({
            code:0x00CD,
            unit:"%",
            tip:"点3转矩百分比",
            description:"发动机在怠速点3的转矩百分比",
            valueMin:-125,
            valueMax:130,
            fmt:"%d"
        });
        argsArray.push({
            code:0x00CE,
            unit:"%",
            tip:"点4转矩百分比",
            description:"发动机在怠速点4的转矩百分比",
            valueMin:-125,
            valueMax:130,
            fmt:"%d"
        });

        for(var i=0;i<argsArray.length;i++){
            connection.query("insert into t_drive_condition set ?",argsArray[i]);
        }

        console.log(argsArray);
        connection.release();
    });
};
